# Import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.core.debugger import set_trace
import json
from matplotlib import colors
from ast import literal_eval

# Load data

In [2]:
# psynet 11
fname = "manu-test-ising1"
fname = "singing-musicians-June-2026"

PATH = f"data/{fname}/"
nodes = pd.read_csv(PATH + "CustomNode.csv", low_memory=False)
# networks = pd.read_csv(PATH + "CustomNetwork.csv", low_memory=False) # old psynet
trials = pd.read_csv(PATH + "CustomTrial.csv", low_memory=False)

In [3]:
print(nodes)

     vars    id        creation_time  failed  failed_reason  time_of_death  \
0      {}    17  2026-05-12 13:20:05   False            NaN            NaN
1      {}    18  2026-05-12 13:20:05   False            NaN            NaN
2      {}    19  2026-05-12 13:20:05   False            NaN            NaN
3      {}    20  2026-05-12 13:20:05   False            NaN            NaN
4      {}    21  2026-05-12 13:20:05   False            NaN            NaN
...   ...   ...                  ...     ...            ...            ...
1100   {}  1117  2026-06-05 13:43:44   False            NaN            NaN
1101   {}  1118  2026-06-05 13:43:56   False            NaN            NaN
1102   {}  1119  2026-06-05 13:44:09   False            NaN            NaN
1103   {}  1120  2026-06-05 13:44:21   False            NaN            NaN
1104   {}  1121  2026-06-05 13:44:33   False            NaN            NaN

             type  network_id  participant_id   trial_maker_id  ... parent_id  \
0     TrialSource          17               3  imitation_chain  ...       NaN
1     TrialSource          18               3  imitation_chain  ...       NaN
2     TrialSource          19               3  imitation_chain  ...       NaN
3     TrialSource          20               3  imitation_chain  ...       NaN
4     TrialSource          21               3  imitation_chain  ...       NaN
...           ...         ...             ...              ...  ...       ...
1100   CustomNode         141              32  imitation_chain  ...    1114.0
1101   CustomNode         137              32  imitation_chain  ...    1112.0
1102   CustomNode         141              32  imitation_chain  ...    1117.0
1103   CustomNode         138              32  imitation_chain  ...    1113.0
1104   CustomNode         139              32  imitation_chain  ...    1116.0

                                                   seed  \
0     {"register": "high", "reference_pitch": 59.731...
1     {"register": "high", "reference_pitch": 60.941...
2     {"register": "high", "reference_pitch": 61.414...
3     {"register": "high", "reference_pitch": 62.112...
4     {"register": "high", "reference_pitch": 63.022...
...                                                 ...
1100  {"reference_pitch": 63.44152376139428, "regist...
1101  {"reference_pitch": 61.06483482990719, "regist...
1102  {"reference_pitch": 60.379981549785235, "regis...
1103  {"reference_pitch": 59.10388903547433, "regist...
1104  {"reference_pitch": 59.53336152758012, "regist...

                                             definition  context  \
0     {"register": "high", "reference_pitch": 59.731...      NaN
1     {"register": "high", "reference_pitch": 60.941...      NaN
2     {"register": "high", "reference_pitch": 61.414...      NaN
3     {"register": "high", "reference_pitch": 62.112...      NaN
4     {"register": "high", "reference_pitch": 63.022...      NaN
...                                                 ...      ...
1100  {"reference_pitch": 63.44152376139428, "regist...      NaN
1101  {"reference_pitch": 61.06483482990719, "regist...      NaN
1102  {"reference_pitch": 60.379981549785235, "regis...      NaN
1103  {"reference_pitch": 59.10388903547433, "regist...      NaN
1104  {"reference_pitch": 59.53336152758012, "regist...      NaN

      participant_group    block  propagate_failure  n_viable_trials  \
0               default  default              False                1
1               default  default              False                1
2               default  default              False                1
3               default  default              False                1
4               default  default              False                1
...                 ...      ...                ...              ...
1100            default  default              False                1
1101            default  default              False                0
1102            default  default              False                0
1103            default  default              False                0
1104            default  default              False                0

           class  object_type
0     CustomNode         Node
1     CustomNode         Node
2     CustomNode         Node
3     CustomNode         Node
4     CustomNode         Node
...          ...          ...
1100  CustomNode         Node
1101  CustomNode         Node
1102  CustomNode         Node
1103  CustomNode         Node
1104  CustomNode         Node

[1105 rows x 33 columns]

In [4]:
# filter nodes
node_data = nodes
node_data = node_data[node_data["failed"] == False]
node_data = node_data[["id", "network_id", "degree", "trial_maker_id", "definition", "seed"]]
node_data = node_data.sort_values(["network_id", "degree"])
node_data["definition"].iloc[1]

print(node_data['definition'])

0       {"register": "high", "reference_pitch": 59.731...
9       {"reference_pitch": 61.08291241563504, "regist...
11      {"reference_pitch": 60.52760335449275, "regist...
17      {"reference_pitch": 61.49649891433537, "regist...
23      {"reference_pitch": 61.37479592370528, "regist...
                              ...
1086    {"reference_pitch": 58.89304522331387, "regist...
1091    {"reference_pitch": 59.842475128342, "register...
1097    {"reference_pitch": 61.62411243945739, "regist...
1100    {"reference_pitch": 63.44152376139428, "regist...
1102    {"reference_pitch": 60.379981549785235, "regis...
Name: definition, Length: 1105, dtype: object

# Preprocess data

In [8]:
# filter nodes
node_data = nodes
node_data = node_data[node_data["failed"] == False]
node_data = node_data[["id", "network_id", "degree", "trial_maker_id", "definition", "seed"]]
node_data = node_data.sort_values(["network_id", "degree"])

# process node definition
mel_id = []
# register = []
trial_type = []
target_pitches = []
target_intervals = []
reference_pitch = []
target_note_durations = []

for i in range(len(node_data)):
    print()
    # definition = node_data["definition"].to_numpy()[i]
    # definition = literal_eval(definition)
    # definition = [d["content"] for d in definition if d["is_center"]][0]

    definition_str = node_data["definition"].iloc[i]  # Access the string directly
    print(definition_str)
    definition = json.loads(definition_str)  # Parse JSON string into dictionary
    # definition = [d["content"] for d in definition if d["is_center"]][0]
    
    # mel_id.append(definition["mel_id"])
    # register.append(definition["register"])
    trial_type.append(definition["trial_type"])
    target_pitches.append(definition["target_pitches"])
    reference_pitch.append(definition["reference_pitch"])
    target_intervals.append(definition["target_intervals"])

# node_data["mel_id"] = mel_id
# node_data["register"] = register
node_data["trial_type"] = trial_type
node_data["target_pitches"] = target_pitches
node_data["reference_pitch"] = reference_pitch
node_data["target_intervals"] = target_intervals

{"register": "high", "reference_pitch": 59.731018325479795, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [53.68399922936616, 57.40811868578826, 57.05767002267592], "target_intervals": [3.724119456422102, -0.35044866311233847], "target_intervals2reference": [-6.047019096113637, -2.322899639691535, -2.6733483028038734], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 61.08291241563504, "register": "high", "target_pitches": [55.27080518097104, 59.05203125066438, 58.32163985006641], "target_intervals": [3.7812260696933393, -0.7303914005979664], "target_intervals2reference": [-5.812107234664005, -2.0308811649706655, -2.761272565568632], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.52760335449275, "register": "high", "target_pitches": [55.102270938473566, 58.314846963992494, 57.10173579457562], "target_intervals": [3.2125760255189277, -1.2131111694168766], "target_intervals2reference": [-5.425332416019181, -2.212756390500253, -3.4258675599171298], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.49649891433537, "register": "high", "target_pitches": [56.39892078508289, 59.56488597569569, 58.40463362621055], "target_intervals": [3.165965190612795, -1.160252349485141], "target_intervals2reference": [-5.097578129252476, -1.931612938639681, -3.091865288124822], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.37479592370528, "register": "high", "target_pitches": [56.08071294651859, 59.3833862730152, 58.355946957598874], "target_intervals": [3.3026733264966097, -1.0274393154163235], "target_intervals2reference": [-5.29408297718669, -1.9914096506900805, -3.018848966106404], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.50046707939832, "register": "high", "target_pitches": [54.93861317808795, 57.69513255202542, 56.500737055612404], "target_intervals": [2.756519373937472, -1.1943954964130157], "target_intervals2reference": [-4.561853901310371, -1.8053345273728993, -2.999730023785915], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.367381656779315, "register": "high", "target_pitches": [56.83929810644211, 59.74576445816562, 58.52527693603457], "target_intervals": [2.906466351723509, -1.2204875221310445], "target_intervals2reference": [-4.528083550337207, -1.6216171986136985, -2.842104720744743], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.928653449587976, "register": "high", "target_pitches": [55.165268070354294, 58.227382848416354, 57.096416643737804], "target_intervals": [3.0621147780620603, -1.1309662046785505], "target_intervals2reference": [-4.763385379233682, -1.7012706011716219, -2.8322368058501723], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.65668719822352, "register": "high", "target_pitches": [58.172291482776664, 60.7614560779188, 59.46778991939765], "target_intervals": [2.5891645951421367, -1.2936661585211482], "target_intervals2reference": [-4.484395715446858, -1.8952311203047216, -3.18889727882587], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.736968948435326, "register": "high", "target_pitches": [53.608526875844376, 56.84130196935855, 55.679525754141046], "target_intervals": [3.232775093514171, -1.1617762152175004], "target_intervals2reference": [-5.12844207259095, -1.895666979076779, -3.0574431942942795], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.37988304708182, "register": "high", "target_pitches": [56.55898233464091, 59.49651924288044, 58.43174596429284], "target_intervals": [2.9375369082395295, -1.0647732785876016], "target_intervals2reference": [-4.82090071244091, -1.8833638042013803, -2.948137082788982], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 60.941216614697524, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [60.263033539891055, 68.15496347403109, 64.24941686384008], "target_intervals": [7.8919299341400375, -3.90554661019101], "target_intervals2reference": [-0.6781830748064692, 7.213746859333568, 3.3082002491425584], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 60.55066212963094, "register": "high", "target_pitches": [60.061178297566016, 67.54943962544684, 63.78177270408498], "target_intervals": [7.488261327880828, -3.767666921361865], "target_intervals2reference": [-0.48948383206492707, 6.998777495815901, 3.2311105744540356], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.3074700794438, "register": "high", "target_pitches": [60.75345465182955, 68.46559230935082, 64.49015022486964], "target_intervals": [7.712137657521268, -3.9754420844811804], "target_intervals2reference": [-0.554015427614253, 7.158122229907015, 3.1826801454258344], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.175214967713416, "register": "high", "target_pitches": [60.83282075825346, 68.10909947962656, 64.240897822704], "target_intervals": [7.276278721373103, -3.8682016569225652], "target_intervals2reference": [-0.3423942094599539, 6.933884511913149, 3.065682854990584], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.424970070201404, "register": "high", "target_pitches": [61.071295963060045, 68.43281381166699, 64.33493657651164], "target_intervals": [7.361517848606937, -4.097877235155352], "target_intervals2reference": [-0.3536741071413587, 7.007843741465578, 2.9099665063102265], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.01908913836706, "register": "high", "target_pitches": [61.96731135350011, 68.90730736676338, 64.80019611204713], "target_intervals": [6.9399960132632685, -4.107111254716244], "target_intervals2reference": [-0.05177778486694962, 6.888218228396319, 2.7811069736800746], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.06047169514224, "register": "high", "target_pitches": [63.03111123946114, 69.84006957635751, 65.47283298329546], "target_intervals": [6.80895833689636, -4.367236593062032], "target_intervals2reference": [-0.02936045568110046, 6.77959788121526, 2.412361288153228], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.23774836922467, "register": "high", "target_pitches": [60.87899382712904, 67.93663149654904, 63.34033639813918], "target_intervals": [7.0576376694199965, -4.596295098409854], "target_intervals2reference": [-0.35875454209563173, 6.698883127324365, 2.1025880289145107], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.2496370881153, "register": "high", "target_pitches": [61.158336718196885, 68.12558131411033, 63.302875747174646], "target_intervals": [6.967244595913449, -4.822705566935689], "target_intervals2reference": [-0.0913003699184145, 6.875944225995035, 2.053238659059346], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.486671446805566, "register": "high", "target_pitches": [60.27772357600002, 67.44876547132168, 62.24251638772393], "target_intervals": [7.1710418953216575, -5.206249083597747], "target_intervals2reference": [-0.20894787080554522, 6.962094024516112, 1.7558449409183652], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.95425620579195, "register": "high", "target_pitches": [60.77527300769777, 68.07187210698618, 62.81546917647963], "target_intervals": [7.2965990992884, -5.256402930506539], "target_intervals2reference": [-0.17898319809417984, 7.11761590119422, 1.8612129706876814], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 61.414453087644674, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [69.62179794055369, 69.979380246241, 62.08251738089378], "target_intervals": [0.3575823056873162, -7.896862865347224], "target_intervals2reference": [8.207344852909017, 8.564927158596333, 0.6680642932491097], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 62.992754704696665, "register": "high", "target_pitches": [71.27351384657952, 72.14547431750786, 63.55198226982858], "target_intervals": [0.8719604709283431, -8.593492047679284], "target_intervals2reference": [8.280759141882854, 9.152719612811197, 0.5592275651319127], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.39948825403945, "register": "high", "target_pitches": [69.15062769116352, 70.69539625527545, 62.028881143049695], "target_intervals": [1.5447685641119477, -8.666515112225767], "target_intervals2reference": [7.751139437124067, 9.295908001236015, 0.6293928890102478], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.7710641398899, "register": "high", "target_pitches": [69.39374927798434, 70.99028226682358, 62.0591221514511], "target_intervals": [1.5965329888392432, -8.931160115372478], "target_intervals2reference": [7.6226851380944325, 9.219218126933676, 0.2880580115611977], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.55287083327436, "register": "high", "target_pitches": [68.9954701541846, 70.61076949701504, 61.65622664265003], "target_intervals": [1.6152993428304399, -8.954542854365016], "target_intervals2reference": [7.442599320910247, 9.057898663740687, 0.10335580937567102], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.21235786152122, "register": "high", "target_pitches": [69.61184182402448, 71.80541250186438, 62.43246508017389], "target_intervals": [2.193570677839901, -9.37294742169049], "target_intervals2reference": [7.399483962503261, 9.593054640343162, 0.22010721865267158], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.69853087043471, "register": "high", "target_pitches": [66.96845025350777, 69.45569213353821, 60.075583620127254], "target_intervals": [2.487241880030439, -9.380108513410946], "target_intervals2reference": [7.269919383073052, 9.757161263103491, 0.3770527496925453], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.802430741460654, "register": "high", "target_pitches": [66.16593247642766, 67.60477339906647, 59.12171850964036], "target_intervals": [1.4388409226388177, -8.483054889426114], "target_intervals2reference": [7.363501734967002, 8.80234265760582, 0.3192877681797057], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.01912674249333, "register": "high", "target_pitches": [69.12897115473659, 71.25644501860394, 62.00383002031454], "target_intervals": [2.127473863867351, -9.252614998289403], "target_intervals2reference": [7.1098444122432625, 9.237318276110614, -0.015296722178788968], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.230121068435935, "register": "high", "target_pitches": [66.22719911415669, 68.29965599878656, 59.18571706325534], "target_intervals": [2.0724568846298723, -9.113938935531223], "target_intervals2reference": [6.997078045720755, 9.069534930350628, -0.04440400518059562], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.758159586217374, "register": "high", "target_pitches": [69.49807486879571, 71.90811111496545, 62.132570325752155], "target_intervals": [2.4100362461697387, -9.775540789213295], "target_intervals2reference": [6.7399152825783375, 9.149951528748076, -0.6255892604652189], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 62.112215199610525, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [65.00066414141128, 55.55647007881868, 63.05985093194337], "target_intervals": [-9.4441940625926, 7.503380853124696], "target_intervals2reference": [2.8884489418007533, -6.555745120791848, 0.9476357323328486], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 62.073844843749725, "register": "high", "target_pitches": [64.60932890360442, 55.40249468693818, 62.62883200232463], "target_intervals": [-9.206834216666238, 7.226337315386452], "target_intervals2reference": [2.5354840598546886, -6.671350156811549, 0.5549871585749031], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.999326231903495, "register": "high", "target_pitches": [63.600391055089176, 54.23697042575721, 61.52088802925763], "target_intervals": [-9.36342062933197, 7.28391760350042], "target_intervals2reference": [2.6010648231856806, -6.762355806146289, 0.5215617973541313], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.72496853987417, "register": "high", "target_pitches": [63.45510884291499, 54.29507191856709, 61.139847196434346], "target_intervals": [-9.1600369243479, 6.844775277867257], "target_intervals2reference": [2.7301403030408196, -6.42989662130708, 0.41487865656017675], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.403529882752935, "register": "high", "target_pitches": [66.02222995275883, 56.896304023446746, 63.852488191732064], "target_intervals": [-9.125925929312082, 6.9561841682853185], "target_intervals2reference": [2.618700070005893, -6.507225859306189, 0.4489583089791296], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.044854692526776, "register": "high", "target_pitches": [62.39770215230016, 53.300080271208884, 60.457107610949215], "target_intervals": [-9.097621881091278, 7.157027339740331], "target_intervals2reference": [2.352847459773386, -6.744774421317892, 0.41225291842243905], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.53240398321569, "register": "high", "target_pitches": [61.88339958266822, 52.98984741063618, 60.098053932984286], "target_intervals": [-8.893552172032038, 7.108206522348105], "target_intervals2reference": [2.3509955994525313, -6.542556572579507, 0.5656499497685985], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.70478319798727, "register": "high", "target_pitches": [64.22221414594003, 55.16388377067359, 62.46250827439061], "target_intervals": [-9.058330375266436, 7.298624503717015], "target_intervals2reference": [2.517430947952761, -6.540899427313676, 0.7577250764033394], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.10225103496808, "register": "high", "target_pitches": [61.641422618568384, 52.74491567546428, 59.93464167756574], "target_intervals": [-8.896506943104107, 7.189726002101466], "target_intervals2reference": [2.5391715836003073, -6.3573353595038, 0.8323906425976659], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.718812803907106, "register": "high", "target_pitches": [61.375253202965986, 52.22738550490589, 59.52977400323551], "target_intervals": [-9.147867698060097, 7.30238849832962], "target_intervals2reference": [2.65644039905888, -6.4914272990012165, 0.8109611993284034], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.97937639006051, "register": "high", "target_pitches": [62.58390037334425, 53.416982333618826, 60.525922733688645], "target_intervals": [-9.166918039725424, 7.1089404000698195], "target_intervals2reference": [2.604523983283741, -6.562394056441683, 0.5465463436281368], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 63.02263398264527, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [62.28155254205641, 60.18227436262309, 72.86922344252865], "target_intervals": [-2.0992781794333197, 12.68694907990556], "target_intervals2reference": [-0.7410814405888573, -2.840359620022177, 9.846589459883383], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 58.89846460993406, "register": "high", "target_pitches": [58.32589606571774, 56.09023098398629, 68.42239093730382], "target_intervals": [-2.2356650817314545, 12.332159953317529], "target_intervals2reference": [-0.5725685442163169, -2.8082336259477714, 9.523926327369757], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.51176700349013, "register": "high", "target_pitches": [61.18939916170309, 58.60409939603821, 70.6954109031052], "target_intervals": [-2.5852997656648853, 12.09131150706699], "target_intervals2reference": [-0.3223678417870346, -2.90766760745192, 9.18364389961507], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.3322742277369, "register": "high", "target_pitches": [63.196528920119356, 60.38154802542591, 72.68755160435651], "target_intervals": [-2.8149808946934485, 12.3060035789306], "target_intervals2reference": [-0.13574530761754744, -2.950726202310996, 9.355277376619604], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.9151692423537, "register": "high", "target_pitches": [62.86522650810985, 60.24845418566134, 72.4808001016545], "target_intervals": [-2.6167723224485115, 12.232345915993157], "target_intervals2reference": [-0.04994273424384943, -2.666715056692361, 9.565630859300796], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.13208710952703, "register": "high", "target_pitches": [62.80347585313127, 60.58083051753815, 72.52787765334466], "target_intervals": [-2.222645335593114, 11.9470471358065], "target_intervals2reference": [-0.32861125639576017, -2.5512565919888743, 9.395790543817625], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.17200350191743, "register": "high", "target_pitches": [59.971460973937376, 57.588679540800584, 69.4028885892329], "target_intervals": [-2.382781433136792, 11.81420904843231], "target_intervals2reference": [-0.20054252798005479, -2.5833239611168466, 9.230885087315464], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.07058953763291, "register": "high", "target_pitches": [62.831557521007014, 60.40910522630253, 72.02823888792253], "target_intervals": [-2.4224522947044846, 11.619133661619998], "target_intervals2reference": [-0.2390320166258988, -2.6614843113303834, 8.957649350289614], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.42112029099509, "register": "high", "target_pitches": [59.20229747845717, 56.959170445309084, 67.97858500719656], "target_intervals": [-2.2431270331480846, 11.019414561887473], "target_intervals2reference": [-0.21882281253792257, -2.461949845686007, 8.557464716201466], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.698617069897686, "register": "high", "target_pitches": [59.415928492998596, 57.076666578947595, 68.64532779718607], "target_intervals": [-2.3392619140510007, 11.568661218238468], "target_intervals2reference": [-0.28268857689909055, -2.6219504909500913, 8.946710727288377], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.81793642509257, "register": "high", "target_pitches": [60.49157987463834, 57.89543442533075, 69.59401633103099], "target_intervals": [-2.596145449307592, 11.69858190570023], "target_intervals2reference": [-0.3263565504542285, -2.9225019997618205, 8.77607990593841], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 62.637121096906405, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [65.9179573152455, 57.976519371647, 60.89091506039095], "target_intervals": [-7.941437943598501, 2.9143956887439515], "target_intervals2reference": [3.280836218339097, -4.660601725259404, -1.7462060365154528], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}


In [9]:
node_data

,id,network_id,degree,trial_maker_id,definition,seed,trial_type,target_pitches,reference_pitch,target_intervals
0,17,17,0,imitation_chain,"{""register"": ""high"", ""reference_pitch"": 59.731...","{""register"": ""high"", ""reference_pitch"": 59.731...",source_trial,"[53.68399922936616, 57.40811868578826, 57.0576...",59.731018,"[3.724119456422102, -0.35044866311233847]"
9,26,17,1,imitation_chain,"{""reference_pitch"": 61.08291241563504, ""regist...","{""reference_pitch"": 61.08291241563504, ""regist...",node_trial,"[55.27080518097104, 59.05203125066438, 58.3216...",61.082912,"[3.7812260696933393, -0.7303914005979664]"
11,28,17,2,imitation_chain,"{""reference_pitch"": 60.52760335449275, ""regist...","{""reference_pitch"": 60.52760335449275, ""regist...",node_trial,"[55.102270938473566, 58.314846963992494, 57.10...",60.527603,"[3.2125760255189277, -1.2131111694168766]"
17,34,17,3,imitation_chain,"{""reference_pitch"": 61.49649891433537, ""regist...","{""reference_pitch"": 61.49649891433537, ""regist...",node_trial,"[56.39892078508289, 59.56488597569569, 58.4046...",61.496499,"[3.165965190612795, -1.160252349485141]"
23,40,17,4,imitation_chain,"{""reference_pitch"": 61.37479592370528, ""regist...","{""reference_pitch"": 61.37479592370528, ""regist...",node_trial,"[56.08071294651859, 59.3833862730152, 58.35594...",61.374796,"[3.3026733264966097, -1.0274393154163235]"
...,...,...,...,...,...,...,...,...,...,...
1086,1103,141,6,imitation_chain,"{""reference_pitch"": 58.89304522331387, ""regist...","{""reference_pitch"": 58.89304522331387, ""regist...",node_trial,"[57.80033692039233, 52.61737193396052, 51.7999...",58.893045,"[-5.182964986431813, -0.8174685580957615]"
1091,1108,141,7,imitation_chain,"{""reference_pitch"": 59.842475128342, ""register...","{""reference_pitch"": 59.842475128342, ""register...",node_trial,"[58.78337548301649, 53.60398925902839, 52.7028...",59.842475,"[-5.179386223988104, -0.9011604184889848]"
1097,1114,141,8,imitation_chain,"{""reference_pitch"": 61.62411243945739, ""regist...","{""reference_pitch"": 61.62411243945739, ""regist...",node_trial,"[60.45838719545648, 55.43485407387196, 54.5156...",61.624112,"[-5.023533121584521, -0.9191648230793916]"
1100,1117,141,9,imitation_chain,"{""reference_pitch"": 63.44152376139428, ""regist...","{""reference_pitch"": 63.44152376139428, ""regist...",node_trial,"[62.16830843665183, 57.218638785203595, 56.802...",63.441524,"[-4.949669651448232, -0.4162298072021642]"
1102,1119,141,10,imitation_chain,"{""reference_pitch"": 60.379981549785235, ""regis...","{""reference_pitch"": 60.379981549785235, ""regis...",node_trial,"[59.138663695538774, 54.423419143398824, 53.27...",60.379982,"[-4.71524455213995, -1.152968088540959]"

# Export node data to csv

In [10]:
node_data.to_csv(f"{fname}_node_data.csv")

# Trial level data

In [11]:
# filter trials
trial_data = trials
trial_data = trial_data[trial_data["failed"] == False]

degrees = []

for i in range(len(trial_data)):
    current_node_id = trial_data.iloc[i]["origin_id"]
    current_nodes = node_data[node_data["id"] == current_node_id]
    current_degree = current_nodes["degree"].to_numpy()[0]
    # answer = d['listen_and_rate_trial_seed']['valence']
    # current_vertex_id = current_nodes["vertex_id"].to_numpy()[0]
    # current_dependent_vertex_ids = current_nodes["dependent_vertex_ids"].to_numpy()[0]
    degrees.append(current_degree)
    # vertex_ids.append(current_vertex_id)
    # dependent_vertex_ids.append(current_dependent_vertex_ids)

trial_data["degree"] = degrees

trial_data = trial_data[["id", "network_id", "degree", "trial_maker_id", "origin_id", "participant_id", "analysis"]]
trial_data = trial_data.sort_values(["network_id", "degree"])

/var/folders/v7/s8wj18ld78gdbf0vgx1ptf7r0000gr/T/ipykernel_13294/4239617211.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data["degree"] = degrees

In [12]:
trial_data

,id,network_id,degree,trial_maker_id,origin_id,participant_id,analysis
4,17,17,0,imitation_chain,17,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
6,19,17,1,imitation_chain,26,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
12,25,17,2,imitation_chain,28,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
18,31,17,3,imitation_chain,34,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
20,33,17,4,imitation_chain,40,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
...,...,...,...,...,...,...,...
1274,1560,141,5,imitation_chain,1097,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1279,1565,141,6,imitation_chain,1103,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1287,1573,141,7,imitation_chain,1108,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1290,1576,141,8,imitation_chain,1114,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1292,1578,141,9,imitation_chain,1117,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."

# Export trial data to csv

In [13]:
trial_data.to_csv(f"{fname}_trial_data.csv")

# Experiment Cost and Demographics

In [14]:
participants = pd.read_csv(PATH + "participant.csv", low_memory=False)

In [15]:
valid_participants = participants[participants["complete"] == True]
valid_participants = valid_participants[valid_participants["failed"] == False]
experiment_summary = {
    "N_participants": valid_participants.shape[0],
    "cost": participants["base_pay"].sum() + participants["bonus"].sum()
}

experiment_summary

{'N_participants': 24, 'cost': 0.0}