# Import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.core.debugger import set_trace
import json
from matplotlib import colors
from ast import literal_eval

# Load data

In [2]:
# psynet 11
fname = "manu-test-ising1"

PATH = f"data/{fname}/"
nodes = pd.read_csv(PATH + "CustomNode.csv", low_memory=False)
# networks = pd.read_csv(PATH + "CustomNetwork.csv", low_memory=False) # old psynet
trials = pd.read_csv(PATH + "CustomTrial.csv", low_memory=False)

In [3]:
print(nodes)

    vars   id        creation_time  failed  failed_reason  time_of_death  \
0     {}   17  2026-04-28 17:15:13   False            NaN            NaN
1     {}   18  2026-04-28 17:15:13   False            NaN            NaN
2     {}   19  2026-04-28 17:15:13   False            NaN            NaN
3     {}   20  2026-04-28 17:15:13   False            NaN            NaN
4     {}   21  2026-04-28 17:15:13   False            NaN            NaN
..   ...  ...                  ...     ...            ...            ...
759   {}  776  2026-04-30 09:13:23   False            NaN            NaN
760   {}  777  2026-04-30 09:13:41   False            NaN            NaN
761   {}  778  2026-04-30 09:13:50   False            NaN            NaN
762   {}  779  2026-04-30 09:13:59   False            NaN            NaN
763   {}  780  2026-04-30 09:14:07   False            NaN            NaN

            type  network_id  participant_id   trial_maker_id  ... parent_id  \
0    TrialSource          17               2  imitation_chain  ...       NaN
1    TrialSource          18               2  imitation_chain  ...       NaN
2    TrialSource          19               2  imitation_chain  ...       NaN
3    TrialSource          20               2  imitation_chain  ...       NaN
4    TrialSource          21               2  imitation_chain  ...       NaN
..           ...         ...             ...              ...  ...       ...
759   CustomNode         101              23  imitation_chain  ...     771.0
760   CustomNode          99              23  imitation_chain  ...     773.0
761   CustomNode         100              23  imitation_chain  ...     772.0
762   CustomNode          97              23  imitation_chain  ...     775.0
763   CustomNode          98              23  imitation_chain  ...     774.0

                                                  seed  \
0    {"register": "high", "reference_pitch": 63.455...
1    {"register": "high", "reference_pitch": 62.147...
2    {"register": "high", "reference_pitch": 61.456...
3    {"register": "high", "reference_pitch": 59.796...
4    {"register": "high", "reference_pitch": 61.077...
..                                                 ...
759  {"reference_pitch": 58.50323955755315, "regist...
760  {"reference_pitch": 63.22744278433368, "regist...
761  {"reference_pitch": 62.02083459806798, "regist...
762  {"reference_pitch": 60.46645306886603, "regist...
763  {"reference_pitch": 61.2755138541487, "registe...

                                            definition  context  \
0    {"register": "high", "reference_pitch": 63.455...      NaN
1    {"register": "high", "reference_pitch": 62.147...      NaN
2    {"register": "high", "reference_pitch": 61.456...      NaN
3    {"register": "high", "reference_pitch": 59.796...      NaN
4    {"register": "high", "reference_pitch": 61.077...      NaN
..                                                 ...      ...
759  {"reference_pitch": 58.50323955755315, "regist...      NaN
760  {"reference_pitch": 63.22744278433368, "regist...      NaN
761  {"reference_pitch": 62.02083459806798, "regist...      NaN
762  {"reference_pitch": 60.46645306886603, "regist...      NaN
763  {"reference_pitch": 61.2755138541487, "registe...      NaN

     participant_group    block  propagate_failure  n_viable_trials  \
0              default  default              False                1
1              default  default              False                1
2              default  default              False                1
3              default  default              False                0
4              default  default              False                1
..                 ...      ...                ...              ...
759            default  default              False                0
760            default  default              False                0
761            default  default              False                0
762            default  default              False                0
763            default  default              False                0

          class  object_type
0    CustomNode         Node
1    CustomNode         Node
2    CustomNode         Node
3    CustomNode         Node
4    CustomNode         Node
..          ...          ...
759  CustomNode         Node
760  CustomNode         Node
761  CustomNode         Node
762  CustomNode         Node
763  CustomNode         Node

[764 rows x 33 columns]

In [5]:
# filter nodes
node_data = nodes
node_data = node_data[node_data["failed"] == False]
node_data = node_data[["id", "network_id", "degree", "trial_maker_id", "definition", "seed"]]
node_data = node_data.sort_values(["network_id", "degree"])
node_data["definition"].iloc[1]

print(node_data['definition'])

0      {"register": "high", "reference_pitch": 63.455...
7      {"reference_pitch": 59.905623453969525, "regis...
12     {"reference_pitch": 63.37257169706941, "regist...
1      {"register": "high", "reference_pitch": 62.147...
8      {"reference_pitch": 62.71431526939736, "regist...
                             ...
742    {"reference_pitch": 60.9008456904601, "registe...
746    {"reference_pitch": 63.31695363831831, "regist...
752    {"reference_pitch": 61.78532810216342, "regist...
754    {"reference_pitch": 61.960961592893284, "regis...
759    {"reference_pitch": 58.50323955755315, "regist...
Name: definition, Length: 764, dtype: object

# Preprocess data

In [7]:
# filter nodes
node_data = nodes
node_data = node_data[node_data["failed"] == False]
node_data = node_data[["id", "network_id", "degree", "trial_maker_id", "definition", "seed"]]
node_data = node_data.sort_values(["network_id", "degree"])

# process node definition
mel_id = []
# register = []
trial_type = []
target_pitches = []
reference_pitch = []
target_note_durations = []

for i in range(len(node_data)):
    print()
    # definition = node_data["definition"].to_numpy()[i]
    # definition = literal_eval(definition)
    # definition = [d["content"] for d in definition if d["is_center"]][0]

    definition_str = node_data["definition"].iloc[i]  # Access the string directly
    print(definition_str)
    definition = json.loads(definition_str)  # Parse JSON string into dictionary
    # definition = [d["content"] for d in definition if d["is_center"]][0]
    
    # mel_id.append(definition["mel_id"])
    # register.append(definition["register"])
    trial_type.append(definition["trial_type"])
    target_pitches.append(definition["target_pitches"])
    reference_pitch.append(definition["reference_pitch"])
    target_intervals.append(definition["target_intervals"])

# node_data["mel_id"] = mel_id
# node_data["register"] = register
node_data["trial_type"] = trial_type
node_data["target_pitches"] = target_pitches
node_data["reference_pitch"] = reference_pitch
node_data["target_intervals"] = target_intervals

{"register": "high", "reference_pitch": 63.45586659211666, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [71.97890171718197, 70.80946991384941, 61.649540345058185], "target_intervals": [-1.1694318033325573, -9.159929568791227], "target_intervals2reference": [8.523035125065313, 7.353603321732756, -1.8063262470584718], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 59.905623453969525, "register": "high", "target_pitches": [68.19130124093152, 66.7376844040187, 58.23899185096494], "target_intervals": [-1.4536168369128148, -8.498692553053758], "target_intervals2reference": [8.28567778696199, 6.832060950049176, -1.666631603004582], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.37257169706941, "register": "high", "target_pitches": [71.68087582862606, 70.3526284620336, 61.15191480591019], "target_intervals": [-1.32824736659245, -9.200713656123412], "target_intervals2reference": [8.308304131556639, 6.980056764964189, -2.220656891159223], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 62.147933363626905, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [57.0874865808037, 55.159023703645786, 66.81778302616162], "target_intervals": [-1.9284628771579122, 11.658759322515834], "target_intervals2reference": [-5.060446782823206, -6.988909659981118, 4.669849662534716], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 62.71431526939736, "register": "high", "target_pitches": [57.4134865885825, 55.0419626949176, 66.99879227903936], "target_intervals": [-2.3715238936649, 11.956829584121763], "target_intervals2reference": [-5.30082868081486, -7.67235257447976, 4.2844770096420035], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.10775481228755, "register": "high", "target_pitches": [56.657826698507, 55.184692344436755, 67.05083214639667], "target_intervals": [-1.4731343540702468, 11.866139801959918], "target_intervals2reference": [-6.449928113780551, -7.923062467850798, 3.9430773341091196], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 61.45699713210087, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [64.0010432721729, 60.33318863175966, 55.81466200927227], "target_intervals": [-3.667854640413232, -4.518526622487393], "target_intervals2reference": [2.5440461400720267, -1.1238085003412053, -5.642335122828598], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 60.03654909121975, "register": "high", "target_pitches": [61.92429166671075, 58.399603582824824, 53.85553432019364], "target_intervals": [-3.524688083885927, -4.544069262631183], "target_intervals2reference": [1.8877425754910035, -1.6369455083949234, -6.181014771026106], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.814592620340214, "register": "high", "target_pitches": [61.362436711519955, 57.62721304064438, 52.93821430719228], "target_intervals": [-3.735223670875577, -4.688998733452095], "target_intervals2reference": [1.5478440911797406, -2.187379579695836, -6.8763783131479315], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 59.796263282186416, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [66.46774968424177, 51.960313171189775, 67.68021081200729], "target_intervals": [-14.507436513051992, 15.719897640817514], "target_intervals2reference": [6.671486402055351, -7.835950110996642, 7.8839475298208725], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"register": "high", "reference_pitch": 61.07792813754913, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [69.7900057970802, 63.136370891527605, 53.94507293285558], "target_intervals": [-6.653634905552593, -9.191297958672024], "target_intervals2reference": [8.712077659531069, 2.0584427539784755, -7.1328552046935485], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 62.261633111836545, "register": "high", "target_pitches": [70.67316887250146, 64.2661906663813, 58.463568332836466], "target_intervals": [-6.406978206120144, -5.802622333544846], "target_intervals2reference": [8.411535760664911, 2.0045575545447676, -3.7980647790000788], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.34638273724262, "register": "high", "target_pitches": [70.72303802811864, 63.51949882691292, 57.94023442996061], "target_intervals": [-7.2035392012057144, -5.579264396952311], "target_intervals2reference": [8.376655290876016, 1.1731160896703017, -4.40614830728201], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 61.59943918148863, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [53.24308696857336, 54.74743067394762, 63.51264080486682], "target_intervals": [1.5043437053742608, 8.7652101309192], "target_intervals2reference": [-8.356352212915269, -6.852008507541008, 1.9132016233781926], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 59.97842622332304, "register": "low", "target_pitches": [53.18341775778929, 53.36864890150766, 61.18711372730354], "target_intervals": [0.18523114371836868, 7.818464825795878], "target_intervals2reference": [-6.795008465533748, -6.609777321815379, 1.2086875039804994], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.778451377563, "register": "low", "target_pitches": [56.16516317647228, 56.28021589458272, 62.60775424874787], "target_intervals": [0.11505271811044082, 6.327538354165149], "target_intervals2reference": [-5.613288201090725, -5.498235482980284, 0.8293028711848649], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.12770978713799, "register": "low", "target_pitches": [56.25011786543376, 56.2821473617764, 62.27628460404874], "target_intervals": [0.03202949634264485, 5.994137242272338], "target_intervals2reference": [-6.87759192170423, -6.845562425361585, -0.8514251830892476], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.820003866247, "register": "low", "target_pitches": [52.004763768721276, 52.377216999102004, 57.89729465028531], "target_intervals": [0.372453230380728, 5.520077651183307], "target_intervals2reference": [-7.815240097525724, -7.442786867144996, -1.9227092159616888], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.71019185272673, "register": "low", "target_pitches": [52.463939042130534, 52.57795781135131, 56.754270784108144], "target_intervals": [0.11401876922077747, 4.176312972756833], "target_intervals2reference": [-6.2462528105961965, -6.132234041375419, -1.9559210686185864], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.59801408893549, "register": "low", "target_pitches": [56.7274519643924, 56.437187238317435, 60.35262395962803], "target_intervals": [-0.290264726074966, 3.9154367213105985], "target_intervals2reference": [-4.870562124543092, -5.160826850618058, -1.2453901293074594], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.91091647130238, "register": "low", "target_pitches": [55.10237755720237, 55.31647869322519, 59.37892880252545], "target_intervals": [0.2141011360228262, 4.062450109300258], "target_intervals2reference": [-5.808538914100012, -5.594437778077186, -1.531987668776928], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.109105527436796, "register": "low", "target_pitches": [55.993099571272275, 55.65203562744579, 59.99084732397472], "target_intervals": [-0.34106394382648375, 4.3388116965289285], "target_intervals2reference": [-5.116005956164521, -5.457069899991005, -1.1182582034620765], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.812758877835584, "register": "low", "target_pitches": [57.828089163747784, 57.62699557587903, 62.055702412299595], "target_intervals": [-0.20109358786875475, 4.428706836420567], "target_intervals2reference": [-4.984669714087801, -5.185763301956555, -0.7570564655359888], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 60.79452467312686, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [68.11251749346656, 52.034104037761324, 56.65503211601971], "target_intervals": [-16.07841345570523, 4.6209280782583875], "target_intervals2reference": [7.317992820339697, -8.760420635365534, -4.139492557107147], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 63.428877658218184, "register": "low", "target_pitches": [70.76321749681793, 55.92943720534303, 61.89034823629076], "target_intervals": [-14.833780291474909, 5.9609110309477344], "target_intervals2reference": [7.334339838599753, -7.499440452875156, -1.5385294219274215], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.56948098968006, "register": "low", "target_pitches": [68.80855398198109, 54.64961427917525, 60.63408089195244], "target_intervals": [-14.158939702805839, 5.98446661277719], "target_intervals2reference": [6.239072992301033, -7.919866710504806, -1.9354000977276158], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.32678007224487, "register": "low", "target_pitches": [66.94644401967925, 52.687742126428, 57.79967754101334], "target_intervals": [-14.25870189325125, 5.111935414585339], "target_intervals2reference": [5.6196639474343755, -8.639037945816874, -3.5271025312315345], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.354666630321326, "register": "low", "target_pitches": [69.98452016133353, 56.052257437070715, 61.42350060585932], "target_intervals": [-13.93226272426282, 5.371243168788602], "target_intervals2reference": [7.629853531012209, -6.302409193250611, -0.9311660244620086], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.66184848738617, "register": "low", "target_pitches": [65.78434108870081, 51.2443943153626, 57.82072214482113], "target_intervals": [-14.539946773338215, 6.576327829458535], "target_intervals2reference": [7.12249260131464, -7.417454172023575, -0.8411263425650404], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.10772077760682, "register": "low", "target_pitches": [66.17915201290687, 55.71801839962472, 60.07701746026787], "target_intervals": [-10.46113361328215, 4.35899906064315], "target_intervals2reference": [5.071431235300047, -5.389702377982104, -1.0307033173389542], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.692067339783314, "register": "low", "target_pitches": [64.51000912100082, 54.393805462694466, 58.46255755764962], "target_intervals": [-10.116203658306347, 4.068752094955151], "target_intervals2reference": [4.817941781217499, -5.298261877088848, -1.2295097821336967], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.16217559968777, "register": "low", "target_pitches": [68.32111146845452, 57.943982641016895, 62.520799147150825], "target_intervals": [-10.37712882743763, 4.57681650613393], "target_intervals2reference": [5.158935868766754, -5.218192958670876, -0.6413764525369459], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.96525335789068, "register": "low", "target_pitches": [67.99742389417614, 58.05248253805007, 61.72042094164282], "target_intervals": [-9.944941356126058, 3.66793840359275], "target_intervals2reference": [5.032170536285449, -4.91277081984061, -1.24483241624786], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.84131286758459, "register": "low", "target_pitches": [65.92813147319188, 56.638150638113494, 60.253493213787685], "target_intervals": [-9.289980835078396, 3.615342575674191], "target_intervals2reference": [4.086818605607299, -5.203162229471097, -1.587819653796906], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 59.08776172475939, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [59.70786191818339, 66.32113545144696, 56.63574588446258], "target_intervals": [6.613273533263573, -9.685389566984384], "target_intervals2reference": [0.6201001934240011, 7.233373726687574, -2.4520158402968093], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 61.09849265593981, "register": "low", "target_pitches": [60.399723152417806, 67.48342975993633, 59.031210582056175], "target_intervals": [7.083706607518522, -8.452219177880153], "target_intervals2reference": [-0.6987695035220014, 6.384937103996521, -2.067282073883632], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.10032770718298, "register": "low", "target_pitches": [62.9077313250385, 67.72189895312664, 60.89722716965738], "target_intervals": [4.81416762808815, -6.82467178346927], "target_intervals2reference": [-0.1925963821444796, 4.62157124594367, -2.2031005375256], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.036552337876756, "register": "low", "target_pitches": [61.51447990818867, 66.90363962746852, 58.98657844897283], "target_intervals": [5.389159719279853, -7.917061178495693], "target_intervals2reference": [-0.5220724296880874, 4.867087289591765, -3.049973888903928], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.84365297004565, "register": "low", "target_pitches": [57.15500559247853, 62.15326230109389, 54.98807865011357], "target_intervals": [4.998256708615358, -7.1651836509803175], "target_intervals2reference": [-1.688647377567122, 3.309609331048236, -3.8555743199320816], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.23915187332459, "register": "low", "target_pitches": [60.73041980295972, 65.51232664797847, 57.40640160191879], "target_intervals": [4.781906845018746, -8.105925046059681], "target_intervals2reference": [-1.5087320703648643, 3.2731747746538815, -4.8327502714058], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.58043994787279, "register": "low", "target_pitches": [60.65879353262261, 65.54038320911067, 57.37239097615151], "target_intervals": [4.881589676488062, -8.167992232959165], "target_intervals2reference": [-1.92164641525018, 2.959943261237882, -5.208048971721283], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.43177395545132, "register": "low", "target_pitches": [60.16644776335913, 64.10791251853311, 56.728227103531836], "target_intervals": [3.941464755173982, -7.379685415001276], "target_intervals2reference": [-1.2653261920921892, 2.6761385630817927, -4.703546851919484], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.03598281146429, "register": "low", "target_pitches": [59.6355782924469, 63.34211873490003, 55.68630245853145], "target_intervals": [3.7065404424531323, -7.655816276368583], "target_intervals2reference": [-1.4004045190173855, 2.306135923435747, -5.349680352932836], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.528439925332854, "register": "low", "target_pitches": [58.25420071161015, 61.00109877693447, 52.52209426005136], "target_intervals": [2.7468980653243165, -8.479004516883109], "target_intervals2reference": [-0.27423921372270144, 2.472658851601615, -6.0063456652814935], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.21774007510583, "register": "low", "target_pitches": [63.78298371727816, 66.91107362961438, 59.48310659966967], "target_intervals": [3.128089912336229, -7.427967029944718], "target_intervals2reference": [0.5652436421723266, 3.6933335545085555, -3.734633475436162], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 59.771901220879926, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [58.310706965104764, 61.57945584150478, 65.23751492057993], "target_intervals": [3.268748876400018, 3.6580590790751444], "target_intervals2reference": [-1.4611942557751618, 1.807554620624856, 5.4656136997], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 61.69983515678924, "register": "low", "target_pitches": [58.910019391530774, 62.631751046952594, 66.35698626491507], "target_intervals": [3.72173165542182, 3.725235217962478], "target_intervals2reference": [-2.789815765258467, 0.9319158901633529, 4.657151108125831], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.58340269647762, "register": "low", "target_pitches": [55.895621950925694, 59.67283242830768, 64.76628562035114], "target_intervals": [3.777210477381985, 5.093453192043455], "target_intervals2reference": [-6.687780745551926, -2.9105702681699412, 2.182882923873514], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.934433216345, "register": "low", "target_pitches": [54.15317117995872, 57.862043407092266, 62.34247284599627], "target_intervals": [3.708872227133547, 4.480429438904004], "target_intervals2reference": [-7.781262036386281, -4.0723898092527335, 0.4080396296512703], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.648675911103005, "register": "low", "target_pitches": [51.2982560463282, 54.18883482038323, 59.227366464910965], "target_intervals": [2.8905787740550295, 5.038531644527737], "target_intervals2reference": [-7.350419864774807, -4.459841090719777, 0.5786905538079594], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.921840657366275, "register": "low", "target_pitches": [53.73866990832219, 56.0567691533816, 59.83895566273982], "target_intervals": [2.3180992450594147, 3.782186509358219], "target_intervals2reference": [-5.183170749044088, -2.865071503984673, 0.917115005373546], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.079249301277926, "register": "low", "target_pitches": [58.33598612405491, 60.62278718996674, 64.67799146312953], "target_intervals": [2.286801065911831, 4.0552042731627935], "target_intervals2reference": [-4.743263177223014, -2.4564621113111826, 1.5987421618516109], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.339979843143375, "register": "low", "target_pitches": [55.49851115781427, 57.78574669545164, 61.69628569430922], "target_intervals": [2.287235537637372, 3.910538998857575], "target_intervals2reference": [-4.8414686853291045, -2.5542331476917326, 1.3563058511658426], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.59800991453816, "register": "low", "target_pitches": [52.963195785132896, 54.77154163296722, 59.593244432984214], "target_intervals": [1.8083458478343246, 4.821702800016993], "target_intervals2reference": [-5.634814129405264, -3.826468281570939, 0.995234518446054], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.629473998682904, "register": "low", "target_pitches": [57.999444121477765, 58.19102761175137, 62.92853752377343], "target_intervals": [0.191583490273608, 4.737509912022055], "target_intervals2reference": [-4.630029877205139, -4.438446386931531, 0.29906352509052425], "num_target_pitches": 3, "trial_type": "node_trial"}


ValueError: Length of values (765) does not match length of index (764)

In [8]:
node_data

,id,network_id,degree,trial_maker_id,definition,seed,trial_type,target_pitches,reference_pitch
0,17,17,0,imitation_chain,"{""register"": ""high"", ""reference_pitch"": 63.455...","{""register"": ""high"", ""reference_pitch"": 63.455...",source_trial,"[71.97890171718197, 70.80946991384941, 61.6495...",63.455867
7,24,17,1,imitation_chain,"{""reference_pitch"": 59.905623453969525, ""regis...","{""reference_pitch"": 59.905623453969525, ""regis...",node_trial,"[68.19130124093152, 66.7376844040187, 58.23899...",59.905623
12,29,17,2,imitation_chain,"{""reference_pitch"": 63.37257169706941, ""regist...","{""reference_pitch"": 63.37257169706941, ""regist...",node_trial,"[71.68087582862606, 70.3526284620336, 61.15191...",63.372572
1,18,18,0,imitation_chain,"{""register"": ""high"", ""reference_pitch"": 62.147...","{""register"": ""high"", ""reference_pitch"": 62.147...",source_trial,"[57.0874865808037, 55.159023703645786, 66.8177...",62.147933
8,25,18,1,imitation_chain,"{""reference_pitch"": 62.71431526939736, ""regist...","{""reference_pitch"": 62.71431526939736, ""regist...",node_trial,"[57.4134865885825, 55.0419626949176, 66.998792...",62.714315
...,...,...,...,...,...,...,...,...,...
742,759,101,5,imitation_chain,"{""reference_pitch"": 60.9008456904601, ""registe...","{""reference_pitch"": 60.9008456904601, ""registe...",node_trial,"[66.15131357088724, 65.99084823487601, 59.7194...",60.900846
746,763,101,6,imitation_chain,"{""reference_pitch"": 63.31695363831831, ""regist...","{""reference_pitch"": 63.31695363831831, ""regist...",node_trial,"[68.31086550238614, 68.55213460727734, 61.9672...",63.316954
752,769,101,7,imitation_chain,"{""reference_pitch"": 61.78532810216342, ""regist...","{""reference_pitch"": 61.78532810216342, ""regist...",node_trial,"[66.65358001173212, 66.4077616839592, 60.31601...",61.785328
754,771,101,8,imitation_chain,"{""reference_pitch"": 61.960961592893284, ""regis...","{""reference_pitch"": 61.960961592893284, ""regis...",node_trial,"[67.14630614716489, 66.83072839328892, 59.9116...",61.960962
759,776,101,9,imitation_chain,"{""reference_pitch"": 58.50323955755315, ""regist...","{""reference_pitch"": 58.50323955755315, ""regist...",node_trial,"[63.640994965484175, 63.55972506296626, 56.091...",58.503240

# Export node data to csv

In [9]:
node_data.to_csv(f"{fname}_node_data.csv")

# Trial level data

In [10]:
# filter trials
trial_data = trials
trial_data = trial_data[trial_data["failed"] == False]

degrees = []

for i in range(len(trial_data)):
    current_node_id = trial_data.iloc[i]["origin_id"]
    current_nodes = node_data[node_data["id"] == current_node_id]
    current_degree = current_nodes["degree"].to_numpy()[0]
    # answer = d['listen_and_rate_trial_seed']['valence']
    # current_vertex_id = current_nodes["vertex_id"].to_numpy()[0]
    # current_dependent_vertex_ids = current_nodes["dependent_vertex_ids"].to_numpy()[0]
    degrees.append(current_degree)
    # vertex_ids.append(current_vertex_id)
    # dependent_vertex_ids.append(current_dependent_vertex_ids)

trial_data["degree"] = degrees

trial_data = trial_data[["id", "network_id", "degree", "trial_maker_id", "origin_id", "participant_id", "analysis"]]
trial_data = trial_data.sort_values(["network_id", "degree"])

/var/folders/v7/s8wj18ld78gdbf0vgx1ptf7r0000gr/T/ipykernel_7972/4239617211.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data["degree"] = degrees

In [9]:
trial_data

,id,network_id,degree,trial_maker_id,origin_id,participant_id,analysis
209,604,17,0,imitation_chain,17,42,"{""failed"": false, ""reason"": ""All good"", ""regis..."
341,926,17,1,imitation_chain,452,61,"{""failed"": false, ""reason"": ""All good"", ""regis..."
564,1412,17,2,imitation_chain,607,84,"{""failed"": false, ""reason"": ""All good"", ""regis..."
663,1703,17,3,imitation_chain,860,104,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1494,4321,17,4,imitation_chain,980,301,"{""failed"": false, ""reason"": ""All good"", ""regis..."
...,...,...,...,...,...,...,...
2555,7109,216,6,imitation_chain,3176,473,"{""failed"": false, ""reason"": ""All good"", ""regis..."
2616,7292,216,7,imitation_chain,3202,479,"{""failed"": false, ""reason"": ""All good"", ""regis..."
2666,7365,216,8,imitation_chain,3280,490,"{""failed"": false, ""reason"": ""All good"", ""regis..."
2704,7502,216,9,imitation_chain,3336,499,"{""failed"": false, ""reason"": ""All good"", ""regis..."
2746,7615,216,10,imitation_chain,3385,507,"{""failed"": false, ""reason"": ""All good"", ""regis..."

# Export trial data to csv

In [11]:
trial_data.to_csv(f"{fname}_trial_data.csv")

# Experiment Cost and Demographics

In [12]:
participants = pd.read_csv(PATH + "participant.csv", low_memory=False)

In [13]:
valid_participants = participants[participants["complete"] == True]
valid_participants = valid_participants[valid_participants["failed"] == False]
experiment_summary = {
    "N_participants": valid_participants.shape[0],
    "cost": participants["base_pay"].sum() + participants["bonus"].sum()
}

experiment_summary

{'N_participants': 16, 'cost': 0.0}